---
deployment:
  tasks:
    - export DEPLOYPATH=/home/codespp1/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R blog $DEPLOYPATH
    - /bin/cp -R contact $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R faq $DEPLOYPATH